version: "3.8"
services:
    main:
        build: 
            context: ./RemoxIo
            dockerfile: Dockerfile
    client:
        stdin_open: true
        environment:
            - CHOKIDAR_USEPOLLING=true
        build:
            dockerfile: Dockerfile
            context: ./Remox-App
        volumes:
            - ./:/app
            - /app/node_modules
        ports: 
            - "2000:3000"
    nginx:
        depends_on:
            - api
            - client
            - main
        restart: always
        build:
            dockerfile: Dockerfile
            context: ./nginx
        ports:
            - "80:80"
            - "443:443"
    api:
        build:
            dockerfile: Dockerfile
            context: ./server
        depends_on: 
            - postgres
        volumes:
            - myapp:/usr/src/app
        environment: 
            POSTGRES_PASSWORD: password
            POSTGRES_USER: user
            #POSTGRES_DATABASE: db
            #DATABASE_URL: postgres://user:password@postgres:5432/db
            NODE_ENV: production
            PORT: 3000
        env_file: ./server/.env
        ports:
            - "3000:3000"
    postgres:
        image: postgres:10.4
        ports:
           - "35000:5432"
        environment: 
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
            POSTGRES_DB: "remox"
        volumes: 
           - db-data:/var/lib/postgresql/data/

volumes: 
  db-data:
    driver: local
  myapp:
    driver: local